const MIN_GRID_SIDE_LENGTH = 10;
const MAX_GRID_SIDE_LENGTH = 50;
const GRID_SIZE_IN_PX = 600;
const DIRECTIONS = [
  [1, 0],
  [-1, 0],
  [0, 1],
  [0, -1],
];
const ONE_SECOND_IN_MS = 1000;
const MAZE_GENERATION_ALGORITHMS = {
  WILSON: 'wilson',
  RANDOMIZED_DFS: 'randomized dfs',
};

export {
  MIN_GRID_SIDE_LENGTH,
  MAX_GRID_SIDE_LENGTH,
  GRID_SIZE_IN_PX,
  DIRECTIONS,
  ONE_SECOND_IN_MS,
  MAZE_GENERATION_ALGORITHMS,
};
